name: _
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  bloc: ^9.2.0
  bloc_enhancer:
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.10.5
  bloc_enhancer_gen:
  lints: ^3.0.0
  test: ^1.24.9
