name: bloc_enhancer_gen
description: A code generator for simplifying Bloc event and state classes, enhancing code readability and reducing naming conflicts.

homepage: https://github.com/Couchsurfing/dart-bloc-enhancer
repository: https://github.com/Couchsurfing/dart-bloc-enhancer
issue_tracker: https://github.com/Couchsurfing/dart-bloc-enhancer/issues

topics: ["bloc", "code-generation", "enhance", "state"]

version: 0.7.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  analyzer: ">=7.5.0 <11.0.0"
  bloc: ">=7.0.0"
  bloc_enhancer: ">=0.1.0 <1.0.0"
  build: ">=4.0.0 <5.0.0"
  change_case: ^2.0.1
  code_builder: ^4.11.0
  dart_style: ">=3.0.0 <4.0.0"
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  meta: ">=1.0.0 <2.0.0"
  path: ^1.9.0
  source_gen: ">=3.1.0 <5.0.0"
  source_span: ^1.10.0

dev_dependencies:
  build_runner: ^2.8.0
  build_test: ^3.4.0
  json_serializable: ^6.11.1
  lints: ^3.0.0
